version: 0.2
            
phases:
  build:
    commands:
      - zip lambda.zip index.js bacon-imminent.js
      - cd lambda/bacon-notifier && npm install && zip -r ../../notifier.zip . && cd -
  post_build:
    commands:
      - aws lambda update-function-code --function-name bakin-bacon-bacon-bit-post --zip-file fileb://lambda.zip
      - aws lambda update-function-code --function-name bakin-bacon-bacon-bit-get --zip-file fileb://lambda.zip
      - aws lambda update-function-code --function-name bakin-bacon-bacon-imminent-post --zip-file fileb://lambda.zip
      - aws lambda update-function-code --function-name bakin-bacon-bacon-notifier --zip-file fileb://notifier.zip
artifacts:
  files:
    - lambda.zip
    - notifier.zip
  discard-paths: yes
